### ISSUE TITLE
infect3d - Risk of incorrect collateral valuation when Chainlink price outside of min/max range

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-04-interest-rate-model-judging#115]
infect3d

medium

# Risk of incorrect collateral valuation when Chainlink price outside of min/max range

## Summary
Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band. The result is that if an asset experiences a huge drop in value, the price of the oracle will continue to return the minPrice instead of the actual price of the asset.

This lets users buy cheaply and borrow against it disproportionately in Exactly markets.

## Vulnerability Detail

This would allow a user to buy the asset at a very cheap price on the open market, deposit it in Exactly and borrow another asset for an amount that shouldn't be possible based on real price.

Example:
TokenA has a minPrice of $1. The price of TokenA drops to $0.10. The aggregator still returns $1 allowing the user to borrow against TokenA as if it is $1 which is 10x it's actual value.

## Impact
Risk of bad debt in case of asset crashes, representing a loss of fund for the protocol.

## Code Snippet

- https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L326-L332
```solidity
File: contracts/Auditor.sol
321:   /// @notice Gets the asset price of a price feed.
322:   /// @dev If Chainlink's asset price is <= 0 the call is reverted.
323:   /// @param priceFeed address of Chainlink's Price Feed aggregator used to query the asset price.
324:   /// @return The price of the asset scaled to 18-digit decimals.
325:   function assetPrice(IPriceFeed priceFeed) public view returns (uint256) {
326:     if (address(priceFeed) == BASE_FEED) return basePrice;
327: 
328:     int256 price = priceFeed.latestAnswer();
329:     if (price <= 0) revert InvalidPrice();
330:     return uint256(price) * baseFactor;
331:   }
```

- https://github.com/sherlock-audit/2024-04-interest-rate-model//blob/main/protocol/contracts/PriceFeedWrapper.sol#L30-L37
- https://github.com/sherlock-audit/2024-04-interest-rate-model//blob/main/protocol/contracts/PriceFeedPool.sol#L35-L45
- https://github.com/sherlock-audit/2024-04-interest-rate-model//blob/main/protocol/contracts/PriceFeedDouble.sol#L27-L29

## Tool used
Manual Review

## Recommendation
StableOracle contracts should check the returned answer against the minPrice/maxPrice and revert if the answer is outside of the bounds:

**Comment by InfectedIsm** [comment]
escalate

Hi @santipu03, I think you might be mixing two different things here: liveness checks and min/max ranges of oracles. 

**Liveness** checks are typically about ensuring that the oracle is actively updating its data and not just frozen or stuck. It's about the freshness and current relevance of the data being provided.

**Min/max ranges**, on the other hand, concern the safety mechanisms that prevent extreme volatility or manipulation by capping the input values an oracle can report. In the case of Chainlink, if the asset price falls outside the min/max range, it defaults to either the minimum or maximum set price rather than reflecting real-time market values.

The issue here isn't about the oracle's liveness or trusting it; it's about how these safeguards can create scenarios where the value of the collateral doesn't accurately reflect market conditions, potentially leading to disproportionate borrowing. 

This discrepancy can lead to significant financial risks for the platform if not properly addressed, regardless of the reliability or trust in Chainlink's data feeds.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> Hi @santipu03, I think you might be mixing two different things here: liveness checks and min/max ranges of oracles. 
> 
> **Liveness** checks are typically about ensuring that the oracle is actively updating its data and not just frozen or stuck. It's about the freshness and current relevance of the data being provided.
> 
> **Min/max ranges**, on the other hand, concern the safety mechanisms that prevent extreme volatility or manipulation by capping the input values an oracle can report. In the case of Chainlink, if the asset price falls outside the min/max range, it defaults to either the minimum or maximum set price rather than reflecting real-time market values.
> 
> The issue here isn't about the oracle's liveness or trusting it; it's about how these safeguards can create scenarios where the value of the collateral doesn't accurately reflect market conditions, potentially leading to disproportionate borrowing. 
> 
> This discrepancy can lead to significant financial risks for the platform if not properly addressed, regardless of the reliability or trust in Chainlink's data feeds.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
I still think this issue can be considered a _known issue_ according to the README:

> Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED? If these integrations are trusted, should auditors also assume they are always responsive, for example, are oracles trusted to provide non-stale information, or VRF providers to respond within a designated timeframe?
>
>Chainlink is TRUSTED.

From reading the above snippet, it's assumed that Chainlink is a trusted party not to provide non-stale information, therefore I assume that is not necessary to do min/max range checks. 

However, as I explained in issue 235, the lack of clarity on the README regarding the Chainlink functionality leads to confusion and different interpretations.

**Comment by InfectedIsm** [comment]
> I still think this issue can be considered a _known issue_ according to the README:
> 
> > Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED? If these integrations are trusted, should auditors also assume they are always responsive, for example, are oracles trusted to provide non-stale information, or VRF providers to respond within a designated timeframe?
> > Chainlink is TRUSTED.
> 
> From reading the above snippet, it's assumed that Chainlink is a trusted party not to provide non-stale information, therefore I assume that is not necessary to do min/max range checks.
> 
> However, as I explained in issue 235, the lack of clarity on the README regarding the Chainlink functionality leads to confusion and different interpretations.

Hi @santipu03, I appreciate your commitment to strictly following Sherlock rules.
But again I think your misinterpreting my submission, there is no lack of trust involved here. 
What I'm describing is the normal behavior of Chainlink if chainlink is trusted.
There is no mention or reference to stale data in my submission.
Chainlink oracles shows 2 parameters, minAnswer and maxAnswer, which are safeguards against flash crashes. If the price go beyond there limit, the oracle will return one of these limits. 
This is what is expected from the oracle, and that's why developers must account for it when reading prices:
- https://github.com/sherlock-audit/2023-05-ironbank-judging/issues/25
- https://github.com/sherlock-audit/2023-05-USSD-judging/issues/598

Thanks again for your time

**Comment by santipu03** [comment]
The head of judging will have the final say in this.

**Comment by cvetanovv** [comment]
This issue is Invalid.

The Readme clearly states that Chainlink is TRUSTED:
> Chainlink is TRUSTED.

This means everything related to Chainlink is a known issue/acceptable risk.

Planning to reject the escalation and leave the issue as is.

**Comment by InfectedIsm** [comment]
Hi @cvetanovv, I appreciate your feedback, but I believe your interpretation of what "trusted" means is wrong.

Let's see what is stated in the readme of the contest:
> Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED? If these integrations are trusted, **should auditors also assume they are always responsive**, for example, **are oracles trusted to provide non-stale information**, or VRF providers to respond within a designated timeframe?
>
> Chainlink is TRUSTED.

My submission is about a price that goes beyond the minAnswer/maxAnswer boundaries, if this happens, **the TRUSTED behavior is that the returned price is one of these boundaries**.
In my case, the oracle is responsive and do not provide stale information. There is no outage of oracle, no bugs, no exploit of/from Chainlink, no trust assumption about Chainlink. 
The trust isn't into Chainlink, but into the collateral asset price that could collapse and cause that issue.

Based on the provided information and documentation, I respectfully believe this does not fit to your interpretation. 
The linked submissions also confirm that.

**Comment by cvetanovv** [comment]
I have understood the rule correctly. The Protocol has clearly written that issues related to Chainlink are known issues.
> We trust Chainlink.

The references you gave to previous issues are from a year ago and are invalid because Chainlink was not TRUSTED in the audit then. 
You can even open the first link you gave as a reference, and you can see that I myself then reported the same issue.

I stand by my initial decision to reject the escalation.

**Comment by InfectedIsm** [comment]
>My submission is about a price that goes beyond the minAnswer/maxAnswer boundaries, if this happens, the TRUSTED behavior is that the returned price is one of these boundaries.
In my case, the oracle is responsive and do not provide stale information. There is no outage of oracle, no bugs, no exploit of/from Chainlink, no trust assumption about Chainlink.
The trust isn't into Chainlink, but into the collateral asset price that could collapse and cause that issue.

@cvetanovv here another way to present it, hopefully you will see what I mean:

A->B->C
Here A (the token) is the root cause of the issue ==> price drop 
Here B (Chainlink) is acting as expected, returning the minAnswer value
Here C (the protocol) suffer an issue from A because it didn't compare the value returned by the oracle to minAnswer to detect the huge price drop

I understand that you will reject the escalation based on a differing interpretation of 'trusted.' 
Can you please, from the above description, clearly explain me how trust in Chainlink is involved here ?

**Comment by cvetanovv** [comment]
The root cause of the issue is that Chainlink Oracle will continue to return the minimum price instead of the asset's actual price. The protocol clearly states that they TRUST the price that comes from Chainlink. 

That is, whether Oracle returns the minimum price (incorrect) or the actual price (correct) is a Known Issue.

Please list any known issues/acceptable risks that should not result in a valid finding.
> We trust Chainlink

As an addition, I can add that the values `minAnswer` and `maxAnswer` are no longer used - [Reference](https://docs.chain.link/data-feeds/api-reference#variables-and-functions-in-accesscontrolledoffchainaggregator)

**Comment by InfectedIsm** [comment]
> The root cause of the issue is that Chainlink Oracle will continue to return the minimum price instead of the asset's actual price. The protocol clearly states that they TRUST the price that comes from Chainlink.
> 
> That is, whether Oracle returns the minimum price (incorrect) or the actual price (correct) is a Known Issue.
> 
> Please list any known issues/acceptable risks that should not result in a valid finding.
> 
> > We trust Chainlink
> 
> As an addition, I can add that the values `minAnswer` and `maxAnswer` are no longer used - [Reference](https://docs.chain.link/data-feeds/api-reference#variables-and-functions-in-accesscontrolledoffchainaggregator)

The link says "on most data feeds", this means it is still used on some.
But then this lower the likelihood of this happening for one of the tokens I agree.

But this is where I do not agree: the price isn't incorrect from a Chainlink perspective, as it return the value it said it will return.

Well, I will end the discussion here as it is going nowhere.As a suggestion, this should be more clearly stated that "any issue implying a trusted source is invalid", rather than "the source is trusted"

Thank you @cvetanovv for the time you spent here, I really respect it. Cheers.

**Comment by cvetanovv** [comment]
Thanks for the discussion. For future contests, this type of issue will be added to Sherlock documentation as Low Severity.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [InfectedIsm](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/115/#issuecomment-2117954843): rejected
