### ISSUE TITLE
0x73696d616f - Users may reduce their post liquidation health factor by splitting assets in several markets

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-interest-rate-model-judging#116]
0x73696d616f

medium

# Users may reduce their post liquidation health factor by splitting assets in several markets

## Summary

Liquidations are performed on a single market at a time, aiming at a `TARGET_HEALTH`. However, this target will likely be unreachable if the positions of the user are split across several markets.

## Vulnerability Detail

Liquidators calling `Market::liquidate()` pick a `seizeMarket`, and the repay market is the market in which the function is called. 

The protocol aims to liquidate users and reach a certain health target, which should not be possible if a user splits its assets across several markets. The debt and collateral that a liquidator can liquidate are capped by the chosen market individual debt and collateral of the liquidatee.

For example, if the user deposits and borrows in a single market, due to the `adjustFactor`, the liquidator should always be able to make the liquidatee reach the health factor target. In case the user decides to split deposits and borrows in 2 markets, it's likely there won't be enough debt or collateral in the individual chosen markets to seize and repay the required total debt across markets to reach the desired health target.

The following test can be added to `Market.t.sol` to confirm that splitting positions across market will lead to smaller liquidations for users.
```solidity
function test_POC_Game_Liquidation() external {
  // setting the same factor for all markets to be sure that it is not because of it
  auditor.setAdjustFactor(market, 0.9e18);

  vm.startPrank(ALICE);

  // ALICE deposits and borrows DAI
  uint256 assets = 10_000 ether;
  ERC20 asset = market.asset();
  deal(address(asset), ALICE, assets);
  market.deposit(assets, ALICE);
  market.borrow(assets*9*9/10/10, ALICE, ALICE);
  
  // ALICE deposits and borrows weth
  deal(address(weth), ALICE, assets);
  weth.approve(address(marketWETH), assets);
  marketWETH.deposit(assets, ALICE);
  marketWETH.borrow(assets*9*9/10/10, ALICE, ALICE);

  vm.stopPrank();

  skip(1);

  // LIQUIDATION
  deal(address(asset), address(market), 100_000 ether);
  address liquidator = makeAddr("liquidator");
  deal(address(asset), liquidator, 100_000_000 ether);
  vm.startPrank(liquidator);
  asset.approve(address(market), type(uint256).max);
  market.liquidate(ALICE, type(uint256).max, market);
  vm.stopPrank();

  // RATIO is smaller than 1.25, liquidator did not liquidate as much as if it was in
  // a single market
  (uint256 collateral, uint256 debt) = auditor.accountLiquidity(address(ALICE), Market(address(0)), 0);
  assertEq(collateral*1e18 / debt, 1108999999911099183);
}
```

## Impact

Increased bad debt and less liquidation incentives.

## Code Snippet

https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L548
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L241-L243
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L248
The limitation of the debt in the repay market as happens when all debt is paid in the repay market and `maxAssets > repaidAssets` [1](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L582), [2](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Market.sol#L593).

## Tool used

Manual Review

Vscode

Foundry

## Recommendation

Implement a cross markets liquidation mechanism to ensure the ratio can reach the target. Instead of specifying one repay market, liquidators could go through all markets, repaying the debt of each market until `maxAssets` is reached.

Duplicate of #155

**Comment by 0x73696d616f** [comment]
Escalate

This is a duplicate of #155, but viewed from a different standpoint. This one focus on the borrower side, while #155 focus on the liquidator side (liquidations should pick lowest LTV). The root cause of both issues is the same, having several markets and only being able to pick one of them to seize/repay. Here I show an explicit recommendation, but #155 mentions that the health factor should improve. Note that fixing this issue fixes #155 and fixing #155 partially fixes this one.

**Comment by Dliteofficial** [comment]
@santipu03 #225 has the same root cause as this issue and I believe they are all valid. Please see #225 for another angle

**Comment by Dliteofficial** [comment]
> This was a design choice, we don't want to make the liquidation process more complex taking into account that even though the account may not reach the target health factor in a single liquidation, multiple liquidations can happen sequentially.

@itofarina how about the fact that liquidations wont only be handled by the liquidation bot. As per your docs, you also expect independent liquidators to participate in liquidations as well. I don't think multiple market liquidations incentivizes them

**Comment by 0x73696d616f** [comment]
I don't think #225 mentions the correct impact which is that the health factor will be off.

**Comment by Dliteofficial** [comment]
> I don't think #225 mentions the correct impact which is that the health factor will be off.

Yes, that's because this issue I believe affect more than the health factor but also the cost of liquidation to the protocol and independent liquidators.

If the liquidator doesn't have the repay market token, he has to incur a swap cost, causing the incentive to to go out the window. Plus, liquidation bot for the protocol is not immediate, it has to wait for a few event before its call

**Comment by santipu03** [comment]
> This is a duplicate of https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155, but viewed from a different standpoint. This one focus on the borrower side, while https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 focus on the liquidator side (liquidations should pick lowest LTV). The root cause of both issues is the same, having several markets and only being able to pick one of them to seize/repay. Here I show an explicit recommendation, but https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 mentions that the health factor should improve. Note that fixing this issue fixes https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 and fixing https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 partially fixes this one.

By the same rule, it should also be a duplicate of #117 right? All three root causes are that a borrower has collateral in several markets but a liquidator can only pick one of them to seize/repay.

**Comment by 0x73696d616f** [comment]
>  By the same rule, it should also be a duplicate of https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/117 right? All three root causes are that a borrower has collateral in several markets but a liquidator can only pick one of them to seize/repay.

This would be true if the rest of the comment also applied here, which is not the case. What I mean by the root cause being having several markets is that both #155 and #116 are strictly attributing as root cause this fact. So while #117 would not happen if there was a single market, ultimately this is not its root cause. #117 attributes the root cause to the incorrect math consideration of not adjusting the average health factor to the adjust factor of the markets to repay and seize. This becomes clear after realizing that the fix for #155 fixes #116, but does not fix #117.

#155 and #116 -> implement cross market liquidations and both are fixed. Or, as #155 suggested, accept this risk but check the post liquidation health factor. This will ensure/mitigate neither the liquidator/protocol take losses (as explained in #155) nor the borrower takes advantage of this (#116).

#117 -> Adjust the health factor to the seize and repay markets, which will ensure that the target health is always 1.25. Neither reports mention a single word about this.

This is the dupping that makes sense.

**Comment by santipu03** [comment]
But fixing #117 will also fix #155 and #116 right?

I mean, if the health factor is adjusted to the seize and repay markets, the post-liquidation health will always be 1.25 so #155 and #116 will also be solved.

**Comment by 0x73696d616f** [comment]
> But fixing https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/117 will also fix https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 and https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116 right? 

No.
> I mean, if the health factor is adjusted to the seize and repay markets, the post-liquidation health will always be 1.25 so https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 and https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116 will also be solved.

This is not how it works. If the picked seize market does not have enough collateral, the target health will not be 1.25. This is the whole point of #155. Only with cross market liquidations can you ensure that the target health is 1.25.

**Comment by santipu03** [comment]
Honestly, maybe I'm missing something but I still don't see quite the difference between #117 and #155. 

I initially grouped them as duplicates because they have the same attack path and impact, and therefore I assume they have the same root cause. 

The attack path of both issues is the following:
1. Borrower has collateral in two markets and becomes liquidatable.
2. Liquidator seizes the collateral with a higher adjust factor.
3. Borrower ends up with a health factor lower than desired.

As far as I can see, the root cause of the underlying issue is that the liquidator is seizing the collateral with a larger adjust factor, therefore causing the final health factor to be lower than expected. This may be fixed by considering the adjust factors of the seize and repay markets (as #117 suggests) or by checking always that the final health factor is not below than initially (as #155 suggests). 

The fact that the final health factor may be below 1.25 after liquidation is a design choice (stated by the sponsor [here](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116#issuecomment-2108644845)) because multiple liquidations can happen sequentially.

**Comment by 0x73696d616f** [comment]
> I assume they have the same root cause.

This is the mistake, they do not have the same root cause. It should be obvious just by looking at the title: `Liquidation does not prioritize lowest LTV tokens` vs `TARGET_HEALTH calculation does not consider the adjust factors of the picked seize and repay markets`. It's clear #155 focus on the seize market picked and #117 focus on the health factor being off regardless of the picked market.

> As far as I can see, the root cause of the underlying issue is that the liquidator is seizing the collateral with a larger adjust factor, therefore causing the final health factor to be lower than expected.

This is the impact, which I think is getting mixed and is where the confusion lies. And even then, this impact that you are mentioning is the impact of #155, picking the wrong adjust factor. #117 does not care which adjust factor you pick, the health factor will always be off. The root cause of #117 is exactly [here](https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L241-L243), when calculating the close factor, while #155 and #116 is being forced to pick one of the markets, and either not having enough collateral to seize (#116) or picking the wrong adjust factor (#155).

> This may be fixed by considering the adjust factors of the seize and repay markets (as https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/117 suggests) or by checking always that the final health factor is not below than initially (as https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/155 suggests).

Both fixes do not mitigate each other. This is what I was explaining [here](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116#issuecomment-2118835702). 

Fix for #117 will not fix #155 or #116 if there is not enough collateral to seize in a single market.
Adjust factor is 1
Target health factor is 1.25
2 markets
1000 debt, 1000 collateral in each market
Liquidator picks a market and gets 1000 collateral, repaying 1000 debt.
Final health factor is 1, not 1.25! (even if the adjust factors are taken into consideration, there's simply not enough collateral in a single market to reach it).
The liquidator has a health factor above 1 and can not be liquidated again.

Fix for #155 or #116 will not fix #117 as the health factor will be off.
Adjust factor is 0.9 and 1
Target health factor is 1.25
2 markets
950 debt, 1000 collateral in each market
Liquidator picks a market and the resulting health factor will be different depending on the picked market or if the picked market does not have enough collateral.

> The fact that the final health factor may be below 1.25 after liquidation is a design choice (stated by the sponsor https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116#issuecomment-2108644845) because multiple liquidations can happen sequentially.

They will not happen sequentially if the resulting health factor is above 1. Also, the sponsor agreed that the bug exists when the same issue was explained via the liquidator's perspective in #155. My recommendation in #116 is the correct fix but the sponsor deems it too complex. The issue is valid, but the sponsor will not apply the recommendation but will use #116's instead.

**Comment by 0x73696d616f** [comment]
@santipu03 look at the example from #155, if we fix the issue, the resulting health factor of the liquidatee is `2.93`, far away from 1.25. This is why we need #117.

**Comment by santipu03** [comment]
Okay, I agree that #155 and #117 have different root causes and this issue (#116) should be a duplicate of #155.

**Comment by 0x73696d616f** [comment]
@santipu03 how are #116 and #117 duplicates? The correct dups are #155 and #116.

**Comment by santipu03** [comment]
My bad, I've corrected it

**Comment by cvetanovv** [comment]
I also agree with the escalation and the Lead Judge. This issue could be a duplicate of #155.

Planning to accept the escalation and duplicate with #155.

**Comment by santiellena** [comment]
@cvetanovv Are you accepting the validity of the issue too?

**Comment by cvetanovv** [comment]
@santiellena Yes, it will be Medium severity. 155 will be the main issue, which is already Medium.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #155

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/116/#issuecomment-2117211593): accepted
