### ISSUE TITLE
ether_sky - The RewardsController has implemented reward allocation incorrectly.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-interest-rate-model-judging#132]
ether_sky

medium

# The RewardsController has implemented reward allocation incorrectly.

## Vulnerability Detail
In the doc, the `borrower incentive rule` is as follows:
```solidity
BI(U) = [w * R(U) * (1 - (1 - delta) * U) + u1] * (1 - sigmoid(U))
```
Here is how it's implemented.
```solidity
function previewAllocation(
  RewardData storage rewardData,
  Market market,
  uint256 deltaTime
) internal view returns (uint256 borrowIndex, uint256 depositIndex, uint256 newUndistributed) {
  v.borrowRewardRule = rewardData  // @audit, here
    .compensationFactor
    .mulWadDown(
      market
        .interestRateModel()
        .floatingRate(m.floatingAssets != 0 ? m.floatingDebt.divWadDown(m.floatingAssets) : 0, v.globalUtilization)
        .mulWadDown(1e18 - v.globalUtilization.mulWadUp(1e18 - market.treasuryFeeRate())) +
        v.borrowAllocationWeightFactor
    )
    .mulWadDown(1e18 - v.sigmoid);
}
```
It is equal to:
```solidity
BI(U) = w * [R(U) * (1 - (1 - delta) * U) + u1] * (1 - sigmoid(U))
```
## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/8f6ef1b0868d3ea3a98a5ab7e8b3a164857681d7/protocol/contracts/RewardsController.sol#L563-L572
## Tool used

Manual Review

## Recommendation
```solidity
function previewAllocation(
  RewardData storage rewardData,
  Market market,
  uint256 deltaTime
) internal view returns (uint256 borrowIndex, uint256 depositIndex, uint256 newUndistributed) {
  v.borrowRewardRule = 
    (rewardData
    .compensationFactor
    .mulWadDown(
      market
        .interestRateModel()
        .floatingRate(m.floatingAssets != 0 ? m.floatingDebt.divWadDown(m.floatingAssets) : 0, v.globalUtilization)
        .mulWadDown(1e18 - v.globalUtilization.mulWadUp(1e18 - market.treasuryFeeRate())) +
-        v.borrowAllocationWeightFactor
+     ) + v.borrowAllocationWeightFactor)
    .mulWadDown(1e18 - v.sigmoid);
}
```

**Comment by santichez** [comment]
Will review this with the team and come back shortly.

**Comment by etherSky111** [comment]
@santichez , any update?

**Comment by santichez** [comment]
We will have a meet about this tomorrow morning.

**Comment by etherSky111** [comment]
?

**Comment by santichez** [comment]
@etherSky111 I tried this change with different tests and the calculated borrow reward rules at the end were the same. Could you please double-check this?

**Comment by etherSky111** [comment]
@santichez , I don't know the reason why you all set `borrowAllocationWeightFactor` to `0` in test.
So the result were the same.
Is this not an important parameter?

**Comment by santichez** [comment]
@etherSky111 that was the reason then, but yes, this finding was a good catch 👍

**Comment by etherSky111** [comment]
Hi @cvetanovv, could you please check this again?

As the report name suggests, the impact is that the rewards distribution is incorrect.
And regarding the attack path, this happens always.
I didn't escalate this because I didn't know whether this is intended behavior or not.
As a result, sponsor skipped this issue at first.
However, the sponsor confirmed that this is incorrect implementation.

**Comment by etherSky111** [comment]
Hi @Evert0x , I want you to check this issue please.
The `rewards distribution` calculation is a little bit complicated and I found the wrong implementation.
The lead judge excluded this issue due to there was no impact and attack path.
However, the wrong rewards distribution itself is an impact and this always happens, so there is no need for a specific attack path.
I didn't escalate due to I was not sure whether there is wrong description in the docs and I thought that the sponsor already checked this.
However, the sponsor confirmed that there was wrong implementation of rewards distribution.

How can we handle this situation?

**Comment by cvetanovv** [comment]
@etherSky111 has discovered a discrepancy in the reward allocation formula, which could lead to significant losses as the rewards are not being calculated accurately. Therefore, this issue deserves a Medium severity.

**Comment by santipu03** [comment]
I marked this issue as invalid because it didn't describe an attack path or an impact, so according to the Sherlock rules it should be invalid. Honestly, I think that approving this issue could be a dangerous precedent for future contests, let's recap on what just happened here:

1. A watson submits a low-effort report like this without specifying any sort of attack path or impact
2. The watson doesn't escalate the issue to not damage his escalations ratio in case of rejection. 
3. The watson confirms the issue with the sponsor, without demonstrating at any point the possible impact that this issue may cause. I mean, the fact that this issue went unnoticed probably means that the impact may not be that critical. 
4. And after all of this, the issue is upgraded to medium severity. 

I find this situation terribly unfair for other watsons who follow the rules, and this could set a precedent for future contests so that watsons get rewarded for sending reports like this and completely bypassing the Sherlock timeline and rules.

**Comment by etherSky111** [comment]
Dear lead judge, could you please recheck my comment?

The impact is wrong reward calculation and there is no need for a specific attack path.
This always happens.
This issue was excluded unfairly due to you didn't check the report carefully.
I checked the math several times and found this issue.

What additional info is needed for this kind of report?

**Comment by etherSky111** [comment]
I didn't escalate this because I didn't know sponsors skipped the excluded issues by lead judge.

I can't believe how you can say easily that this is low-effort report.
For this, I mastered the complicated math formula for this protocol.
And this is best report to describe such obvious issue with my writing skills.

**Comment by santipu03** [comment]
What I meant by this report being low-effort is:
- Less than 20 of your words (excluding title).
- No summary and impact sections.
- No PoC backing your claims.

You've claimed several times that this issue always occurs and leads to significant loss of rewards, however, we still didn't see any PoC to check the real impact of this issue. 

Still, I don't believe it's fair to upgrade this issue now given that it hasn't been escalated. Sherlock has created a detailed system for judging and I think it's unfair that some watson can bypass it as if he was above all rules.

**Comment by etherSky111** [comment]
```
The watson doesn't escalate the issue to not damage his escalations ratio in case of rejection.
```
Regarding this, I have enough ratio.
And I created first escalations in this contest.

**Comment by etherSky111** [comment]
What you mean `upgragde`?
This was reported as medium.
Please stop trying to defend your wrong judge.

**Comment by etherSky111** [comment]
```
Still, I don't believe it's fair to upgrade this issue now given that it hasn't been escalated. Sherlock has created a detailed system for judging and I think it's unfair that @etherSky111 can bypass it as if he was above all rules.
```
Seems like I am a dangerous guy to destroy the Sherlock's rules?

In my past contests, I saw some examples that valid issues were marked finally as invalid by Sherlock when it had obvious invalid reason without escalation.
I think this is the same case.

Anyway, I will respect Sherlock team's decision even though I will experience some unfair results.
So please stop writing comments from your side.

**Comment by 0x73696d616f** [comment]
Agree with @santipu03's comments and would like to add the following.
There is actually no loss of rewards, but they are allocated slightly more/less to depositors than borrowers (we have no idea how much as there is no POC given).
Additionally, there is no real impact as `v.borrowAllocationWeightFactor` is 0 in the tests and on all markets and rewards on [mainnet](https://optimistic.etherscan.io/address/0xBd1ba78A3976cAB420A9203E6ef14D18C2B2E031#readProxyContract), so the math is exactly the same.
Thus, this is an info finding.

**Comment by etherSky111** [comment]
@0x73696d616f , I agree :)
so please stop writing comments.
You can't change the weight of this report.

**Comment by etherSky111** [comment]
I am just happy to improve the protocol's security through Sherlock's contest.
That's enough for me.

**Comment by etherSky111** [comment]
@santichez , thanks for your reviewing this issue.
Although this could be missing in final report, I will be happy if you would consider this issue.

**Comment by cvetanovv** [comment]
@santipu03 and @0x73696d616f have a right. The issue only shows a discrepancy in the formula that has it in the documentation. There is no description of an impact and whether there is one at all. Therefore, this issue will remain invalid due to insufficient quality.
