### ISSUE TITLE
AuditorPraise - latestAnswer() is deprecated

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-interest-rate-model-judging#42]
AuditorPraise

medium

# latestAnswer() is deprecated

## Summary
latestAnswer() is deprecated - https://docs.chain.link/data-feeds/api-reference#latestanswer 
## Vulnerability Detail
According to [chainlink documentation](https://docs.chain.link/data-feeds/api-reference#latestanswer ) The function `latestAnswer()` is deprecated and shouldn't be used.

`latestAnswer()` a chainlink deprecated function is used to retrieve price in Auditor.assetPrice()

i'm sure it is chainlink pricefeed because this comment states so --https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L324
 
## Impact
Using `latestAnswer()` a deprecated function opens protocol to certain risks.
## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/Auditor.sol#L329

## Tool used

Manual Review

## Recommendation
use `latestRoundData()` instead -- https://docs.chain.link/data-feeds/api-reference#latestrounddata-1

**Comment by AuditorPraise** [comment]
@santipu03 This should be valid because chainlink clearly states that latestAnswer() is deprecated and shouldn't be used. **SOURCE**: https://docs.chain.link/data-feeds/api-reference#latestanswer

**Comment by santipu03** [comment]
Only identifying the root cause of an issue without describing an attack path or a valid impact that could lead to a loss of funds is not enough to categorize an issue as duplicate. 

> In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

**Comment by AuditorPraise** [comment]
@santipu03 pls what is the missing impact here?

**`Using latestAnswer() a deprecated function opens protocol to certain risks.`** - i believe this is sufficient impact considering that chainlink has made it obvious that the function is deprecated and shouldn't be used.

**Comment by ABDuullahi** [comment]
Escalate

Based on the above comments.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Based on the above comments.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
This report correctly identifies the same root cause as issue #235. However, I marked this issue as invalid according to the following Sherlock guidelines:

> In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

I agree that the definition of what is a _clear impact_ can be tricky in some situations, but the above rule was put in place to avoid low-effort submissions that just identify a potential problem without digging into the possible risks and impacts. 

I still consider that this report doesn't clearly describe an impact, but I guess that just depends on how you look at it. For me, describing a clear impact means demonstrating how an issue can lead to a loss of funds or disrupt the protocol functionality, and this report has neither of them.

**Comment by AuditorPraise** [comment]
> This report correctly identifies the same root cause as issue #235. However, I marked this issue as invalid according to the following Sherlock guidelines:
> 
> > In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.
> 
> I agree that the definition of what is a _clear impact_ can be tricky in some situations, but the above rule was put in place to avoid low-effort submissions that just identify a potential problem without digging into the possible risks and impacts. 
> 
> I still consider that this report doesn't clearly describe an impact, but I guess that just depends on how you look at it. For me, describing a clear impact means demonstrating how an issue can lead to a loss of funds or disrupt the protocol functionality, and this report has neither of them. 

```
The use of an unsupported and deprecated function can brick the protocol or even lead to exploits considering if the protocol does not make an immediate adjustment to the price feed

The issue should be under scope as the FAQ for the contest although mentions that chainlink is trusted but broken assumptions and future concerns should be reported.
```

Tbh I don't see any difference in the above  impact that #235 has and the impact I gave. 

Just a difference in length and choice of words, they're both referring to the same thing.

And I believe I identified the root cause issue and gave the right mitigation for it. 

Also I submitted it as a medium and not a high unlike #235

**Comment by cvetanovv** [comment]
This issue is a duplicate of #235. This issue doesn't describe things as well as #235, but there are currently more poor-quality reports duplicated with #235, such as #5.

Since #235 has an escalation and will most likely remain invalid, I will reject the escalation so as not to decrease the Lead Judge payout. There is such a rule in the [documentation](https://docs.sherlock.xyz/audits/judging/escalation-period#rules-for-escalation):
> Escalation will not be accepted in case the reward distribution is not affected. 

Planning to reject the escalation and leave the issue as is. If #235 becomes valid, I will accept the escalation and dup with #235.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ABDUullahi](https://github.com/sherlock-audit/2024-04-interest-rate-model-judging/issues/42/#issuecomment-2117969972): rejected
