### ISSUE TITLE
0xumarkhatab - Lack of minimum values parameters for vesting in EscrowEXA

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-interest-rate-model-judging#99]
0xumarkhatab

high

# Lack of minimum values parameters for vesting in EscrowEXA

## Summary
The vest function in escrow contract does provide users the ability to add max params but it does not give users the 
ability to propose the acceptable min values of those parameters which can make some people to lose value when
they are giving the max threshold and not the minimum acceptable values because the contract itself does not support it.

## Vulnerability Detail

```solidity
  function vest(uint128 amount, address to, uint256 maxRatio, uint256 maxPeriod) public returns (uint256 streamId) {
    assert(amount != 0);
    if (reserveRatio > maxRatio || vestingPeriod > maxPeriod) revert Disagreement();

  // snip
  }
```
The protocol checks for upper bounds tolerance of user but it does not provide lower bound tolerance to users which might lead to users losing the value of their tokens.

## Impact
loss of token values for users if undesired lower bounds occur for their token vesting period
## Code Snippet
https://github.com/sherlock-audit/2024-04-interest-rate-model/blob/main/protocol/contracts/periphery/EscrowedEXA.sol#L89

## Tool used

Manual Review

## Recommendation
Allow users to add minReserveRatio and minPeriod too .and let them decide if they want to use max limits or min limits provided by them.

**Comment by 0xumarkhatab** [comment]
@santipu03 sir , i believe that lack of slippage params clearly leads to loss of funds . Everything can not be regarded as improvement suggestion just because its not already there.

Since lack of minimum params specification can lead to loss of funds , I believe its a medium

**Comment by santipu03** [comment]
Can you demonstrate that the lack of lower-bound parameters will lead to a loss of funds?

**Comment by 0xumarkhatab** [comment]
@santipu03  Thank you for asking.

Okay suppose ( taking arbitrary small values to show the impact )

the user passes maxRatio = 20
amount = 1000e18

where as current reserve ratio at time of initiating the transaction was 10
 
The user expects that for this setting ,  that they have to transfer 1000*10 = 10000 exa

`uint256 reserve = amount.mulWadUp(reserveRatio);`

however , the user's transaction gets delayed by 3 blocks 

and the reserve ratio reaches 19 , 

the amount of exa the user has to pay is 
19000 exa

Now the maxRatio has been passed by the user but they did not expect that transaction can be delayed ( due to network congestion and other scenarios )

but since the transaction got delayed , the max ratio was still in the range of maxRatio 

and user end up paying 9000 more exa than they initially calculated if the transaction was to be executed .

The risk appetite of the user might only allowed them to use 10k tokens for vesting but instead the protocol has used 

19k tokens out of their pocket and this can't be reverted easily as its executed.

Now this situation might escalate if the maxRatio passed is always some unit max value ( like uint256.max by some protocols using exactly's EscrowExa )

because they might always want to execute their transaction.

In that case , users will lose a lot of tokens than even imagined.

But if there was a deadline parameter that user can specify  or the max exa tokens they can specify to be used , 

The user would save themselves their funds.

So yeah these are the scenarios

There is a definite loss of funds involved.

Looking forward to your feedback

**Comment by santipu03** [comment]
In your scenario, the user can prevent that issue by setting `maxRatio` to 10 instead of 20. If the user has set `maxRatio` to 20 and the txn executed with a ratio of 19, then there should be no problem because it's assumed that the user is able to pay up to 20_000 EXA.

**Comment by 0xumarkhatab** [comment]
@santipu03 i appreciate your response. 
However as stated , the problem might rise for users who are using this functionality through some protocol and the protocol has added max uint value for maxRatio and that smart contract is immutable. 

The situation will prevail then

Instead the user should be able to add that so that the intermediate protocol might forward that params to the smart contract to ensure timely execution

**Comment by santipu03** [comment]
The smart contracts interacting with the `vest` function should allow users to set their value for `maxRatio`, thus solving the issue. If some protocol doesn't set the `maxRatio` argument correctly when calling `vest`, that is not Exactly's fault and it's deemed out of scope for this contest.

**Comment by 0xumarkhatab** [comment]
Noted !
Yeah its accurate then
